[core.template]
unit = "S7-300"
vendor = "Siemens"
description = "Creates a simple device for IEC 60870-5-104"
protocols = ["IEC104", "SNMP"]
creator = "Patrick Reichenberger"

[core.databus.key_value_mappings]
SystemDescription = "Siemens, SIMATIC, S7-300"
sysObjectID = "0.0"
Uptime = { function = "conpot.emulators.misc.uptime.Uptime" }
sysContact = ""
sysName = ""
sysLocation = ""
sysServices = "72"
ifNumber = 1
ifIndex = 1
ifDescr = "Siemens, SIMATIC NET, CP 343-1 PN, 6GK7 343-1EX21-0XE0, HW: Version 2, FW: Version V1.2.3, Ethernet Port 1, Rack 0, 100Mbit"
ifType = 6
ifMtu = 1000
ifSpeed = 100000000
ifPhysAddress = "0x000e8c29c51a"
ifAdminStatus = 1
ifOperStatus = 1
ifLastChange = { function = "conpot.emulators.misc.uptime.Uptime" }
FacilityName = "Compagnie Generale des Eaux"
0 = 0
1 = 1
ifInOctets = { function = "conpot.emulators.misc.sysinfo.BytesRecv" }
ifInUcastPkts = { function = "conpot.emulators.misc.sysinfo.PacketsRecv" }
ifInNUcastPkts = 291
ifOutOctets = { function = "conpot.emulators.misc.sysinfo.BytesSent" }
ifOutUcastPkts = { function = "conpot.emulators.misc.sysinfo.PacketsSent" }
ifOutUNcastPkts = 143
ipForwarding = 2
ipDefaultTTL = 60
ipInReceives = 31271
ipInHdrErrors = 0
ipInAddrErrors = 0
ipForwDatagrams = 0
ipInUnknownProtos = 0
ipInDiscards = 0
ipInDelivers = 31282
ipOutRequests = 69023
ipOutDiscards = 0
ipOutNoRoutes = 0
ipReasmTimeout = 60
ipReasmReqds = 7
ipReasmOKs = 3
ipReasmFails = 0
ipFragOKs = 0
ipFragFails = 0
ipFragCreates = 0
ipAdEntAddr = { function = "conpot.emulators.misc.sysinfo.LocalIP" }
ipAdEntIfIndex = 1
ipAdEntNetMask = "255.255.255.255"
ipAdEntBcastAddr = 1
ipAdEntReasmMaxSize = 65528
ipRoutingDiscards = 0
icmpInMsgs = 4
icmpInErrors = 0
icmpInDestUnreachs = 1
icmpInTimeExcds = 0
icmpInParmProbs = 0
icmpInSrcQuenchs = 0
icmpInRedirects = 0
icmpInEchos = 0
icmpInEchoReps = 0
icmpInTimestamps = 0
icmpInTimestampReps = 0
icmpInAddrMasks = 0
icmpInAddrMaskReps = 0
icmpOutMsgs = 0
icmpOutErrors = 0
icmpOutDestUnreachs = 144
icmpOutTimeExcds = 0
icmpOutParmProbs = 0
icmpOutSrcQuenchs = 0
icmpOutRedirects = 0
icmpOutEchos = 0
icmpOutEchoReps = 0
icmpOutTimestamps = 0
icmpOutTimestampReps = 0
icmpOutAddrMasks = 0
icmpOutAddrMaskReps = 0
tcpRtoAlgorithm = 2
tcpRtoMin = 0
tcpRtoMax = 100
tcpMaxConn = -1
tcpActiveOpens = 0
tcpPassiveOpens = 101
tcpAttemptFails = 42
tcpEstabResets = 45
tcpCurrEstab = { function = "conpot.emulators.misc.sysinfo.TcpCurrEstab" }
tcpInSegs = 30321
tcpOutSegs = 67821
tcpRetransSegs = 2511
tcpConnState = 2
tcpConnLocalAddress = { function = "conpot.emulators.misc.sysinfo.LocalIP" }
tcpConnLocalPort = 2404
tcpConnRemAddress = "0.0.0.0"
tcpConnRemPort = 0
tcpInErrs = 1
tcpOutRsts = 728
udpInDatagrams = 1441
udpNoPorts = 1280
udpInErrors = 23
udpOutDatagrams = 47
udpLocalAddress = "163.172.189.137"
udpLocalPort = 161
SystemName = "CP 343-1 IT"
CommonAddress = "0x1e28"
T_0 = 30
T_1 = 15
T_2 = 10
T_3 = 20
k = 12
w = 8
MaxFrameSize = 254
13_20 = 1
13_21 = 0
13_22 = 0
13_24 = 1
13_25 = 1
13_32 = 1
13_33 = 1
13_34 = 1
13_35 = 1
13_36 = 1
13_37 = 1
13_38 = 1
13_39 = 1
13_40 = 0
13_41 = 1
13_42 = 0
22_19 = 1
22_20 = 1
22_21 = 0
22_22 = 0
22_24 = 1
22_25 = 1
22_42 = 1
22_43 = 1
22_54 = 1
33_2 = 1
33_3 = 2
33_4 = 1
33_5 = 2
33_6 = 2
33_7 = 1
33_8 = 1
33_9 = 1
33_10 = 1
33_11 = 1
60_6 = 2
60_7 = 1
60_8 = 1
60_9 = 1
60_20 = 1
60_21 = 1
60_32 = 1
60_34 = 1
60_35 = 1
60_36 = 1
100_12 = 103
100_13 = 31
100_51 = -49
100_108 = 28871
100_109 = 13781
100_178 = 119
100_179 = 219
100_190 = 1009
100_191 = -2
100_192 = 701
100_193 = 441
101_63 = 103
101_205 = 31
101_100 = 5
101_101 = 49
101_102 = 119
101_105 = 500
101_106 = 1
107_3 = 16.2
107_77 = 15.9
107_78 = 512.1
107_79 = 433.4
107_90 = 344.4
107_130 = -0.44013
107_131 = 43.0
107_132 = 41.2
107_141 = 12.1
107_200 = 91
107_201 = 98.8
107_202 = 110
107_203 = 85.1
107_204 = 85.2
107_205 = 410
107_206 = 592
107_207 = 1.5
107_208 = 44.7
107_209 = 11.9
107_210 = 221.45
107_211 = 13.4
107_212 = 0.000402
109_3 = 16.2
109_7 = 15.9
109_8 = 880
109_10 = 344.4
109_40 = 41.2
109_41 = 12.1
empty = ""
