[core.template]
unit = "S7-300"
vendor = "Siemens"
description = "Creates a simple device for SNMP"
protocols = ["snmp"]
creator = "Patrick Reichenberger"

[core.databus.key_value_mappings]
SystemDescription = "Siemens, SIMATIC, S7-300"
sysObjectID = "0.0"
Uptime = { function = "conpot.emulators.misc.uptime.Uptime" }
sysContact = ""
sysName = ""
sysLocation = ""
sysServices = "72"
ifNumber = 1
ifIndex = 1
ifDescr = "Siemens, SIMATIC NET, CP 343-1 PN, 6GK7 343-1EX21-0XE0, HW: Version 2, FW: Version V1.2.3, Ethernet Port 1, Rack 0, 100Mbit"
ifType = 6
ifMtu = 1000
ifSpeed = 100000000
ifPhysAddress = "0x000e8c29c51a"
ifAdminStatus = 1
ifOperStatus = 1
ifLastChange = { function = "conpot.emulators.misc.uptime.Uptime" }
FacilityName = "Compagnie Generale des Eaux"
0 = 0
1 = 1
ifInOctets = { function = "conpot.emulators.misc.sysinfo.BytesRecv" }
ifInUcastPkts = { function = "conpot.emulators.misc.sysinfo.PacketsRecv" }
ifInNUcastPkts = 291
ifOutOctets = { function = "conpot.emulators.misc.sysinfo.BytesSent" }
ifOutUcastPkts = { function = "conpot.emulators.misc.sysinfo.PacketsSent" }
ifOutUNcastPkts = 143
ipForwarding = 2
ipDefaultTTL = 60
ipInReceives = 31271
ipInHdrErrors = 0
ipInAddrErrors = 0
ipForwDatagrams = 0
ipInUnknownProtos = 0
ipInDiscards = 0
ipInDelivers = 31282
ipOutRequests = 69023
ipOutDiscards = 0
ipOutNoRoutes = 0
ipReasmTimeout = 60
ipReasmReqds = 7
ipReasmOKs = 3
ipReasmFails = 0
ipFragOKs = 0
ipFragFails = 0
ipFragCreates = 0
ipAdEntAddr = { function = "conpot.emulators.misc.sysinfo.LocalIP" }
ipAdEntIfIndex = 1
ipAdEntNetMask = "255.255.255.255"
ipAdEntBcastAddr = 1
ipAdEntReasmMaxSize = 65528
ipRoutingDiscards = 0
icmpInMsgs = 4
icmpInErrors = 0
icmpInDestUnreachs = 1
icmpInTimeExcds = 0
icmpInParmProbs = 0
icmpInSrcQuenchs = 0
icmpInRedirects = 0
icmpInEchos = 0
icmpInEchoReps = 0
icmpInTimestamps = 0
icmpInTimestampReps = 0
icmpInAddrMasks = 0
icmpInAddrMaskReps = 0
icmpOutMsgs = 0
icmpOutErrors = 0
icmpOutDestUnreachs = 144
icmpOutTimeExcds = 0
icmpOutParmProbs = 0
icmpOutSrcQuenchs = 0
icmpOutRedirects = 0
icmpOutEchos = 0
icmpOutEchoReps = 0
icmpOutTimestamps = 0
icmpOutTimestampReps = 0
icmpOutAddrMasks = 0
icmpOutAddrMaskReps = 0
tcpRtoAlgorithm = 2
tcpRtoMin = 0
tcpRtoMax = 100
tcpMaxConn = -1
tcpActiveOpens = 0
tcpPassiveOpens = 101
tcpAttemptFails = 42
tcpEstabResets = 45
tcpCurrEstab = { function = "conpot.emulators.misc.sysinfo.TcpCurrEstab" }
tcpInSegs = 30321
tcpOutSegs = 67821
tcpRetransSegs = 2511
tcpConnState = 2
tcpConnLocalAddress = { function = "conpot.emulators.misc.sysinfo.LocalIP" }
tcpConnLocalPort = 2404
tcpConnRemAddress = "0.0.0.0"
tcpConnRemPort = 0
tcpInErrs = 1
tcpOutRsts = 728
udpInDatagrams = 1441
udpNoPorts = 1280
udpInErrors = 23
udpOutDatagrams = 47
udpLocalAddress = "163.172.189.137"
udpLocalPort = 161
SystemName = "CP 343-1 IT"
hrSystemUptime = { function = "conpot.emulators.misc.sysinfo.BootTime" }
hrSystemDate = { function = "conpot.emulators.misc.sysinfo.CurrentDatetime" }
hrSystemInitialLoadDevice = 7
hrSystemInitialLoadParameters = ""
hrSystemNumUsers = 1
hrSystemProcesses = 10
hrSystemMaxProcesses = 32
hrMemorySize = { function = "conpot.emulators.misc.sysinfo.TotalRam" }
hrStorageIndex0 = 1
hrStorageIndex1 = 2
hrStorageDescr0 = "CE Object Store"
hrStorageDescr1 = "Virtual Memory"
hrStorageAllocationUnits0 = 1
hrStorageAllocationUnits1 = 65536
hrStorageSize0 = { function = "conpot.emulators.misc.sysinfo.StorageSize" }
hrStorageSize1 = 16384
hrStorageUsed0 = { function = "conpot.emulators.misc.sysinfo.StorageUsed" }
hrStorageUsed1 = 185
hrStorageAllocationFailures0 = 0
hrStorageAllocationFailures1 = 0
hrDeviceIndex1 = 1
hrDeviceIndex2 = 2
hrDeviceIndex3 = 3
hrDeviceIndex4 = 4
hrDeviceIndex5 = 5
hrDeviceIndex6 = 6
hrDeviceIndex7 = 7
hrDeviceIndex8 = 8
hrDeviceIndex9 = 9
hrDeviceDescr1 = "Unknown Processor Type"
hrDeviceDescr2 = "Software Loopback Interface 1"
hrDeviceDescr3 = "FEC1"
hrDeviceDescr4 = "L2TP1"
hrDeviceDescr5 = "PPTP1"
hrDeviceDescr6 = "ASYNCMAC1"
hrDeviceDescr7 = "WinCE Object Store"
hrDeviceDescr8 = "Unknown keyboard"
hrDeviceDescr9 = "COM1:"
hrDeviceStatus1 = 2
hrDeviceStatus2 = 1
hrDeviceStatus3 = 1
hrDeviceStatus4 = 1
hrDeviceStatus5 = 1
hrDeviceStatus6 = 1
hrDeviceStatus7 = 2
hrDeviceStatus8 = 2
hrDeviceStatus9 = 1
hrDeviceErrors1 = 0
hrDeviceErrors2 = 0
hrDeviceErrors3 = 0
hrDeviceErrors4 = 0
hrDeviceErrors5 = 0
hrDeviceErrors6 = 0
hrDeviceErrors7 = 0
hrDeviceErrors8 = 0
hrDeviceErrors9 = 0
hrProcessorLoad = { function = "conpot.emulators.misc.sysinfo.CpuLoad" }
hrNetworkIfIndex2 = 1
hrNetworkIfIndex3 = 2
hrNetworkIfIndex4 = 3
hrNetworkIfIndex5 = 4
hrNetworkIfIndex6 = 5
hrDiskStorageAccess7 = 1
hrDiskStorageMedia7 = 8
hrDiskStorageRemoveble7 = 2
hrDiskStorageCapacity7 = 117604
hrFSIndex1 = 1
hrFSMountPoint1 = "\\"
hrFSRemoteMountPoint1 = ""
hrFSAccess1 = 1
hrFSBootable1 = 2
hrFSStorageIndex1 = 0
hrFSLastFullBackupDate1 = "0-1-1,0:0:0.0"
hrFSLastPartialBackupDate1 = "0-1-1,0:0:0.0"
hrSWOSIndex0 = 4194306
hrSWRunIndex4194306 = 4194306
hrSWRunIndex8126482 = 8126482
hrSWRunIndex17891378 = 17891378
hrSWRunIndex73728034 = 73728034
hrSWRunIndex76939274 = 76939274
hrSWRunIndex77201418 = 77201418
hrSWRunIndex78446594 = 78446594
hrSWRunIndex88211530 = 88211530
hrSWRunIndex93782086 = 93782086
hrSWRunIndex97058862 = 97058862
hrSWRunPath4194306 = ""
hrSWRunPath8126482 = ""
hrSWRunPath17891378 = ""
hrSWRunPath73728034 = ""
hrSWRunPath76939274 = ""
hrSWRunPath77201418 = ""
hrSWRunPath78446594 = ""
hrSWRunPath88211530 = ""
hrSWRunPath93782086 = ""
hrSWRunPath97058862 = ""
hrSWRunParameters4194306 = ""
hrSWRunParameters8126482 = ""
hrSWRunParameters17891378 = ""
hrSWRunParameters73728034 = ""
hrSWRunParameters76939274 = ""
hrSWRunParameters77201418 = ""
hrSWRunParameters78446594 = ""
hrSWRunParameters88211530 = ""
hrSWRunParameters93782086 = ""
hrSWRunParameters97058862 = ""
hrSWRunType4194306 = 2
hrSWRunType8126482 = 4
hrSWRunType17891378 = 4
hrSWRunType73728034 = 4
hrSWRunType76939274 = 4
hrSWRunType77201418 = 4
hrSWRunType78446594 = 4
hrSWRunType88211530 = 4
hrSWRunType93782086 = 4
hrSWRunType97058862 = 4
hrSWRunStatus4194306 = 1
hrSWRunStatus8126482 = 1
hrSWRunStatus17891378 = 1
hrSWRunStatus73728034 = 1
hrSWRunStatus76939274 = 1
hrSWRunStatus77201418 = 1
hrSWRunStatus78446594 = 1
hrSWRunStatus88211530 = 1
hrSWRunStatus93782086 = 1
hrSWRunStatus97058862 = 1
hrSWRunPerfCPU4194306 = 10909
hrSWRunPerfCPU8126482 = 5
hrSWRunPerfCPU17891378 = 11
hrSWRunPerfCPU73728034 = 2136
hrSWRunPerfCPU76939274 = 54
hrSWRunPerfCPU77201418 = 4
hrSWRunPerfCPU78446594 = 3
hrSWRunPerfCPU88211530 = 12
hrSWRunPerfCPU93782086 = 11
hrSWRunPerfCPU97058862 = 11
hrSWRunPerfMem4194306 = 0
hrSWRunPerfMem8126482 = 0
hrSWRunPerfMem17891378 = 0
hrSWRunPerfMem73728034 = 0
hrSWRunPerfMem76939274 = 0
hrSWRunPerfMem77201418 = 0
hrSWRunPerfMem78446594 = 0
hrSWRunPerfMem88211530 = 0
hrSWRunPerfMem93782086 = 0
hrSWRunPerfMem97058862 = 0
