[ads]
enabled = true
host = "0.0.0.0"
port = 48898
timeout = 5
ams_net_id = "192.168.1.1.1.1"
ams_port = 851
device_name = "Conpot TwinCAT"
version_major = 3
version_minor = 1
version_build = 0
ads_state = 5
device_state = 0
discovery_enabled = true
discovery_port = 48899
hostname = "CX-CONPOT"
tc_version_major = 3
tc_version_minor = 1
tc_version_build = 4024
os_platform = 2
os_major = 10
os_minor = 0
os_build = 19045
os_service_pack = ""

[[ads.symbols]]
name = "MAIN.bRunning"
index_group = 16448
index_offset = 0
value_hex = "01"

[[ads.symbols]]
name = "MAIN.nCounter"
index_group = 16448
index_offset = 4
value_hex = "00000000"
