[core.template]
unit = "382"
vendor = "Kamstrup"
description = "Register clone of an existing Kamstrup 382 smart meter"
protocols = ["kamstrup_management", "kamstrup_meter"]
creator = "Johnny Vestergaard"

[core.databus.key_value_mappings]
power_simulator = { function = "conpot.emulators.kamstrup.usage_simulator.UsageSimulator" }
register_1024 = { value = "0" }
register_1 = { value = "0" }
register_2 = { value = "0" }
register_13 = { value = "71832712" }
register_14 = { value = "0" }
register_1054 = { value = "228" }
register_1055 = { value = "229" }
register_1056 = { value = "224" }
register_1076 = { value = "511" }
register_1077 = { value = "422" }
register_1078 = { value = "144" }
register_1080 = { value = "1000" }
register_1081 = { value = "5499" }
register_1082 = { value = "895" }
register_3 = { value = "0" }
register_4 = { value = "0" }
register_5 = { value = "0" }
register_6 = { value = "0" }
register_1025 = { value = "0" }
register_1033 = { value = "0" }
register_1034 = { value = "0" }
register_1035 = { value = "0" }
register_1036 = { value = "0" }
register_15 = { value = "0" }
register_16 = { value = "0" }
register_17 = { value = "0" }
register_18 = { value = "0" }
register_1027 = { value = "0" }
register_20 = { value = "0" }
register_21 = { value = "0" }
register_22 = { value = "0" }
register_23 = { value = "0" }
register_24 = { value = "0" }
register_25 = { value = "0" }
register_26 = { value = "0" }
register_27 = { value = "0" }
register_28 = { value = "0" }
register_29 = { value = "0" }
register_30 = { value = "0" }
register_31 = { value = "0" }
register_32 = { value = "0" }
register_33 = { value = "0" }
register_34 = { value = "0" }
register_35 = { value = "0" }
register_36 = { value = "0" }
register_37 = { value = "0" }
register_38 = { value = "0" }
register_39 = { value = "0" }
register_40 = { value = "0" }
register_41 = { value = "0" }
register_42 = { value = "0" }
register_43 = { value = "0" }
register_44 = { value = "0" }
register_45 = { value = "0" }
register_46 = { value = "0" }
register_1071 = { value = "0" }
register_1072 = { value = "0" }
register_1073 = { value = "0" }
register_50 = { value = "0" }
register_51 = { value = "1258679" }
register_52 = { value = "0" }
register_53 = { value = "0" }
register_54 = { value = "21000002" }
register_55 = { value = "22201011" }
register_56 = { value = "1000" }
register_57 = { value = "0" }
register_58 = { value = "0" }
register_1083 = { value = "34353" }
register_1084 = { value = "256" }
register_1086 = { value = "101110" }
register_1205 = { value = "340282366920938463463374607431768211455" }
register_1092 = { value = "1" }
register_1037 = { value = "0" }
register_1038 = { value = "0" }
register_1112 = { value = "30" }
register_1113 = { value = "30" }
register_1114 = { value = "30" }
register_1039 = { value = "99000" }
register_1121 = { value = "0" }
register_1026 = { value = "0" }
register_1126 = { value = "3820031751153221778937193183286" }
register_19 = { value = "0" }
register_1047 = { value = "9441543881752250126" }
register_1049 = { value = "0" }
register_1050 = { value = "0" }
register_1028 = { value = "0" }
register_1051 = { value = "0" }
register_1189 = { value = "0" }
register_1202 = { value = "340282366920938463463374607431768211455" }
register_1203 = { value = "340282366920938463463374607431768211455" }
register_1204 = { value = "340282366920938463463374607431768211455" }
register_1206 = { value = "340282366920938463463374607431768211455" }
register_1207 = { value = "340282366920938463463374607431768211455" }
register_1208 = { value = "340282366920938463463374607431768211455" }
register_1209 = { value = "340282366920938463463374607431768211455" }
register_1029 = { value = "100" }
register_1058 = { value = "227691635558201180633139" }
register_1115 = { value = "60" }
register_1059 = { value = "0" }
register_1060 = { value = "0" }
register_1030 = { value = "46828625" }
register_1061 = { value = "0" }
register_1062 = { value = "0" }
register_1063 = { value = "0" }
register_1064 = { value = "0" }
register_1065 = { value = "0" }
register_1031 = { value = "0" }
register_1066 = { value = "0" }
register_1067 = { value = "0" }
register_1068 = { value = "0" }
register_1069 = { value = "0" }
register_1070 = { value = "0" }
register_1074 = { value = "0" }
register_1075 = { value = "0" }
register_1079 = { value = "315" }
register_1181 = { value = "433534329705531658" }
register_1001 = { value = "15085488" }
register_1002 = { value = "203513" }
register_1003 = { value = "140727" }
register_1004 = { value = "283" }
register_1005 = { value = "53011401" }
register_1010 = { value = "15085488" }
register_1021 = { value = "0" }
register_1023 = { value = "0" }
reboot_signal = { value = "0" }
software_version = { value = "'5.5 (E5)'" }
access_control_status = { value = "'DISABLED'" }
access_control_1 = { value = "'0.0.0.0'" }
access_control_2 = { value = "'0.0.0.0'" }
access_control_3 = { value = "'0.0.0.0'" }
access_control_4 = { value = "'0.0.0.0'" }
access_control_5 = { value = "'0.0.0.0'" }
device_name = { value = "''" }
nameserver_1 = { value = "'0.0.0.0'" }
nameserver_2 = { value = "'0.0.0.0'" }
nameserver_3 = { value = "'0.0.0.0'" }
mac_address = { value = "'00:13:EA:00:00:00'" }
use_dhcp = { value = "'YES'" }
ip_addr = { value = "'192.168.1.210'" }
ip_gateway = { value = "'192.168.1.1'" }
ip_subnet = { value = "'255.255.255.0'" }
ip_addr_dhcp = { value = "'192.168.0.1'" }
ip_gateway_dhcp = { value = "'192.168.0.254'" }
ip_subnet_dhcp = { value = "'255.255.255.0'" }
kap_a_server_hostname = { value = "'kapserver.evilpowerprovider.org'" }
kap_a_server_ip = { value = "'202.202.202.1'" }
kap_a_server_port = { value = "'50'" }
kap_b_server_ip = { value = "'0.0.0.0'" }
kap_b_server_port = { value = "'50'" }
channel_a_meternumber = { value = "'A1 06 A1 02 B7 34 12 00 00 03'" }
channel_b_meternumber = { value = "'A1 06 A1 02 B7 34 12 00 00 03'" }
channel_a_port = { value = "'1025'" }
channel_b_port = { value = "'1027'" }
kap_ack_server = { value = "'NO'" }
kap_local_port = { value = "'800'" }
alarm_server_status = { value = "'DISABLED'" }
alarm_server_ip = { value = "''" }
alarm_server_port = { value = "'4000'" }
kap_server_lookup = { value = "'0 - none'" }
software_watchdog = { value = "'3600'" }
kap_missing_warning = { value = "'60'" }
keep_alive_timer = { value = "'10'" }
serial_settings_a = { value = "'Auto'" }
serial_settings_b = { value = "'115200,8,E,1'" }
channel_a_connect_socket = { value = "'0 - None'" }
channel_b_connect_socket = { value = "'0 - None'" }
