name: Code tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          architecture: "x64"
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install system packages
        run: sudo apt-get install gcc ipmitool
      - name: Install python dependencies
        run: uv sync --frozen --group dev
      - name: Test with pytest pytest-cov
        run: |
          uv run pytest --junitxml=junit/test-results.xml --cov=conpot --cov-report=xml --cov-report=html
